/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/19/23, 1:16 AM' 
 * Generated by 'Asus' 
 * Generated on server 'SHUBHAM' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:52033/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257B0AF9784D-1430-4FF8-A6C4-84FB9E1FCFDC%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.GLOBALTEMPERATURE out=Work.preProcessedData;
	by dt;
run;

proc arima data=Work.preProcessedData plots
    (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecastonly));
	identify var=LandAndOceanAverageTemperature;
	estimate p=(1) (12) q=(1) (12) method=ML;
	forecast lead=12 back=24 alpha=0.05 id=dt interval=month;
	outlier;
	run;
quit;

proc delete data=Work.preProcessedData;
run;